// Generated by build_readability_plan.py. Windows 2016.07.05 only.
// KnownFields structures intentionally contain only Windows-confirmed fields.
#pragma pack(push, 1)
enum Win335_ZoneDownOpcode : unsigned __int16
{
  Win335_ZoneDownOpcode_ChatToChannel = 0x0067,
  Win335_ZoneDownOpcode_Unknown_0078 = 0x0078,
  Win335_ZoneDownOpcode_Unknown_0079 = 0x0079,
  Win335_ZoneDownOpcode_Unknown_007A = 0x007A,
  Win335_ZoneDownOpcode_Unknown_007B = 0x007B,
  Win335_ZoneDownOpcode_Unknown_007C = 0x007C,
  Win335_ZoneDownOpcode_InviteResult = 0x00C9,
  Win335_ZoneDownOpcode_InviteReplyResult = 0x00CA,
  Win335_ZoneDownOpcode_InviteUpdate = 0x00CB,
  Win335_ZoneDownOpcode_GetCommonlistResult = 0x00CC,
  Win335_ZoneDownOpcode_GetCommonlistDetailResult = 0x00CD,
  Win335_ZoneDownOpcode_SetProfileResult = 0x00CE,
  Win335_ZoneDownOpcode_GetProfileResult = 0x00CF,
  Win335_ZoneDownOpcode_GetSearchCommentResult = 0x00D0,
  Win335_ZoneDownOpcode_ChatChannelResult = 0x00D2,
  Win335_ZoneDownOpcode_SendSystemMessage = 0x00D3,
  Win335_ZoneDownOpcode_SendLoginMessage = 0x00D4,
  Win335_ZoneDownOpcode_UpdateOnlineStatus = 0x00D5,
  Win335_ZoneDownOpcode_PartyRecruitResult = 0x00D6,
  Win335_ZoneDownOpcode_GetRecruitSearchListResult = 0x00D7,
  Win335_ZoneDownOpcode_GetRecruitDetailResult = 0x00D8,
  Win335_ZoneDownOpcode_RequestItmeResult = 0x00D9,
  Win335_ZoneDownOpcode_AllianceReadyCheckResult = 0x00DA,
  Win335_ZoneDownOpcode_GetFcJoinRequestCommentResult = 0x00DB,
  Win335_ZoneDownOpcode_PcPartyResult = 0x00DC,
  Win335_ZoneDownOpcode_PcPartyUpdate = 0x00DD,
  Win335_ZoneDownOpcode_InviteCancelResult = 0x00DE,
  Win335_ZoneDownOpcode_BlacklistAddResult = 0x00E1,
  Win335_ZoneDownOpcode_BlacklistRemoveResult = 0x00E2,
  Win335_ZoneDownOpcode_GetBlacklistResult = 0x00E3,
  Win335_ZoneDownOpcode_Unknown_00E4 = 0x00E4,
  Win335_ZoneDownOpcode_Unknown_00E5 = 0x00E5,
  Win335_ZoneDownOpcode_FriendlistRemoveResult = 0x00E6,
  Win335_ZoneDownOpcode_Unknown_00E7 = 0x00E7,
  Win335_ZoneDownOpcode_PcSearchResult = 0x00EB,
  Win335_ZoneDownOpcode_LinkshellResult = 0x00F0,
  Win335_ZoneDownOpcode_GetLinkshellListResult = 0x00F1,
  Win335_ZoneDownOpcode_LetterResult = 0x00FA,
  Win335_ZoneDownOpcode_GetLetterMessageResult = 0x00FB,
  Win335_ZoneDownOpcode_GetLetterMessageDetailResult = 0x00FC,
  Win335_ZoneDownOpcode_GetLetterStatusResult = 0x00FD,
  Win335_ZoneDownOpcode_ItemSearchResult = 0x0104,
  Win335_ZoneDownOpcode_GetItemSearchListResult = 0x0105,
  Win335_ZoneDownOpcode_GetRetainerListResult = 0x0106,
  Win335_ZoneDownOpcode_BuyMarketRetainerResult = 0x0107,
  Win335_ZoneDownOpcode_MarketStorageUpdate = 0x0108,
  Win335_ZoneDownOpcode_GetItemHistoryResult = 0x0109,
  Win335_ZoneDownOpcode_GetRetainerSalesHistoryResult = 0x010A,
  Win335_ZoneDownOpcode_MarketRetainerUpdate = 0x010B,
  Win335_ZoneDownOpcode_CatalogSearchResult = 0x010C,
  Win335_ZoneDownOpcode_FreeCompanyResult = 0x010E,
  Win335_ZoneDownOpcode_GetFcStatusResult = 0x010F,
  Win335_ZoneDownOpcode_GetFcInviteListResult = 0x0110,
  Win335_ZoneDownOpcode_GetFcProfileResult = 0x0111,
  Win335_ZoneDownOpcode_GetFcHeaderResult = 0x0112,
  Win335_ZoneDownOpcode_GetCompanyBoardResult = 0x0113,
  Win335_ZoneDownOpcode_GetFcHierarchyResult = 0x0114,
  Win335_ZoneDownOpcode_GetFcActivityListResult = 0x0115,
  Win335_ZoneDownOpcode_GetFcHierarchyLiteResult = 0x0116,
  Win335_ZoneDownOpcode_GetCompanyMottoResult = 0x0117,
  Win335_ZoneDownOpcode_GetFcParamsResult = 0x0118,
  Win335_ZoneDownOpcode_GetFcActionResult = 0x0119,
  Win335_ZoneDownOpcode_GetFcMemoResult = 0x011A,
  Win335_ZoneDownOpcode_Unknown_011B = 0x011B,
  Win335_ZoneDownOpcode_Unknown_011C = 0x011C,
  Win335_ZoneDownOpcode_Unknown_011D = 0x011D,
  Win335_ZoneDownOpcode_InfoGMCommandResult = 0x0122,
  Win335_ZoneDownOpcode_SyncTag32 = 0x012D,
  Win335_ZoneDownOpcode_SyncTag64 = 0x012E,
  Win335_ZoneDownOpcode_SyncTag128 = 0x012F,
  Win335_ZoneDownOpcode_SyncTag256 = 0x0130,
  Win335_ZoneDownOpcode_Unknown_0132 = 0x0132,
  Win335_ZoneDownOpcode_Unknown_0133 = 0x0133,
  Win335_ZoneDownOpcode_Unknown_0134 = 0x0134,
  Win335_ZoneDownOpcode_Unknown_0135 = 0x0135,
  Win335_ZoneDownOpcode_Unknown_0136 = 0x0136,
  Win335_ZoneDownOpcode_Unknown_0137 = 0x0137,
  Win335_ZoneDownOpcode_HudParam = 0x0140,
  Win335_ZoneDownOpcode_ActionIntegrity = 0x0141,
  Win335_ZoneDownOpcode_Order = 0x0142,
  Win335_ZoneDownOpcode_OrderMySelf = 0x0143,
  Win335_ZoneDownOpcode_OrderTarget = 0x0144,
  Win335_ZoneDownOpcode_Resting = 0x0145,
  Win335_ZoneDownOpcode_ActionResult1 = 0x0146,
  Win335_ZoneDownOpcode_ActionResult = 0x0147,
  Win335_ZoneDownOpcode_Status = 0x0148,
  Win335_ZoneDownOpcode_FreeCompany = 0x0149,
  Win335_ZoneDownOpcode_RecastGroup = 0x014A,
  Win335_ZoneDownOpcode_UpdateAlliance = 0x014B,
  Win335_ZoneDownOpcode_PartyPos = 0x014C,
  Win335_ZoneDownOpcode_AlliancePos = 0x014D,
  Win335_ZoneDownOpcode_Unknown_014E = 0x014E,
  Win335_ZoneDownOpcode_Unknown_014F = 0x014F,
  Win335_ZoneDownOpcode_Unknown_0150 = 0x0150,
  Win335_ZoneDownOpcode_Unknown_0151 = 0x0151,
  Win335_ZoneDownOpcode_Unknown_0152 = 0x0152,
  Win335_ZoneDownOpcode_Unknown_0153 = 0x0153,
  Win335_ZoneDownOpcode_Unknown_0154 = 0x0154,
  Win335_ZoneDownOpcode_Unknown_0155 = 0x0155,
  Win335_ZoneDownOpcode_Unknown_0156 = 0x0156,
  Win335_ZoneDownOpcode_Unknown_0157 = 0x0157,
  Win335_ZoneDownOpcode_Unknown_0158 = 0x0158,
  Win335_ZoneDownOpcode_Unknown_0159 = 0x0159,
  Win335_ZoneDownOpcode_Unknown_015A = 0x015A,
  Win335_ZoneDownOpcode_Unknown_015B = 0x015B,
  Win335_ZoneDownOpcode_Unknown_0168 = 0x0168,
  Win335_ZoneDownOpcode_Unknown_0169 = 0x0169,
  Win335_ZoneDownOpcode_Unknown_016A = 0x016A,
  Win335_ZoneDownOpcode_Create = 0x0190,
  Win335_ZoneDownOpcode_Delete = 0x0191,
  Win335_ZoneDownOpcode_ActorMove = 0x0192,
  Win335_ZoneDownOpcode_Transfer = 0x0193,
  Win335_ZoneDownOpcode_Warp = 0x0194,
  Win335_ZoneDownOpcode_Unknown_0195 = 0x0195,
  Win335_ZoneDownOpcode_RequestCast = 0x0196,
  Win335_ZoneDownOpcode_Unknown_0197 = 0x0197,
  Win335_ZoneDownOpcode_UpdateParty = 0x0199,
  Win335_ZoneDownOpcode_InitZone = 0x019A,
  Win335_ZoneDownOpcode_HateList = 0x019B,
  Win335_ZoneDownOpcode_HaterList = 0x019C,
  Win335_ZoneDownOpcode_CreateObject = 0x019D,
  Win335_ZoneDownOpcode_DeleteObject = 0x019E,
  Win335_ZoneDownOpcode_PlayerStatusUpdate = 0x019F,
  Win335_ZoneDownOpcode_PlayerStatus = 0x01A0,
  Win335_ZoneDownOpcode_BaseParam = 0x01A1,
  Win335_ZoneDownOpcode_FirstAttack = 0x01A2,
  Win335_ZoneDownOpcode_Condition = 0x01A3,
  Win335_ZoneDownOpcode_ChangeClass = 0x01A4,
  Win335_ZoneDownOpcode_Equip = 0x01A5,
  Win335_ZoneDownOpcode_Inspect = 0x01A6,
  Win335_ZoneDownOpcode_Name = 0x01A7,
  Win335_ZoneDownOpcode_AttachMateriaRequest = 0x01A9,
  Win335_ZoneDownOpcode_RetainerList = 0x01AA,
  Win335_ZoneDownOpcode_RetainerData = 0x01AB,
  Win335_ZoneDownOpcode_MarketPriceHeader = 0x01AC,
  Win335_ZoneDownOpcode_MarketPrice = 0x01AD,
  Win335_ZoneDownOpcode_NormalItem = 0x01AF,
  Win335_ZoneDownOpcode_ItemSize = 0x01B0,
  Win335_ZoneDownOpcode_ItemOperationBatch = 0x01B1,
  Win335_ZoneDownOpcode_ItemOperation = 0x01B2,
  Win335_ZoneDownOpcode_GilItem = 0x01B3,
  Win335_ZoneDownOpcode_TradeCommand = 0x01B4,
  Win335_ZoneDownOpcode_ItemMessage = 0x01B5,
  Win335_ZoneDownOpcode_UpdateItem = 0x01B6,
  Win335_ZoneDownOpcode_AliasItem = 0x01B7,
  Win335_ZoneDownOpcode_OpenTreasure = 0x01B8,
  Win335_ZoneDownOpcode_LootRight = 0x01B9,
  Win335_ZoneDownOpcode_LootActionResult = 0x01BA,
  Win335_ZoneDownOpcode_GameLog = 0x01BB,
  Win335_ZoneDownOpcode_TreasureOpenRight = 0x01BC,
  Win335_ZoneDownOpcode_LootItems = 0x01BE,
  Win335_ZoneDownOpcode_CreateTreasure = 0x01BF,
  Win335_ZoneDownOpcode_TreasureFadeOut = 0x01C0,
  Win335_ZoneDownOpcode_MonsterNoteCategory = 0x01C1,
  Win335_ZoneDownOpcode_EventPlay2 = 0x01C3,
  Win335_ZoneDownOpcode_EventPlay4 = 0x01C4,
  Win335_ZoneDownOpcode_EventPlay8 = 0x01C5,
  Win335_ZoneDownOpcode_EventPlay16 = 0x01C6,
  Win335_ZoneDownOpcode_EventPlay32 = 0x01C7,
  Win335_ZoneDownOpcode_EventPlay64 = 0x01C8,
  Win335_ZoneDownOpcode_EventPlay128 = 0x01C9,
  Win335_ZoneDownOpcode_EventPlay255 = 0x01CA,
  Win335_ZoneDownOpcode_PushEventState = 0x01CC,
  Win335_ZoneDownOpcode_PopEventState = 0x01CD,
  Win335_ZoneDownOpcode_UpdateEventScene2 = 0x01CF,
  Win335_ZoneDownOpcode_UpdateEventScene4 = 0x01D0,
  Win335_ZoneDownOpcode_UpdateEventScene8 = 0x01D1,
  Win335_ZoneDownOpcode_UpdateEventScene16 = 0x01D2,
  Win335_ZoneDownOpcode_Unknown_01D3 = 0x01D3,
  Win335_ZoneDownOpcode_Unknown_01D4 = 0x01D4,
  Win335_ZoneDownOpcode_Unknown_01D5 = 0x01D5,
  Win335_ZoneDownOpcode_Unknown_01D6 = 0x01D6,
  Win335_ZoneDownOpcode_ResumeEventScene2 = 0x01D8,
  Win335_ZoneDownOpcode_ResumeEventScene4 = 0x01D9,
  Win335_ZoneDownOpcode_ResumeEventScene8 = 0x01DA,
  Win335_ZoneDownOpcode_ResumeEventScene16 = 0x01DB,
  Win335_ZoneDownOpcode_ResumeEventScene32 = 0x01DC,
  Win335_ZoneDownOpcode_ResumeEventScene64 = 0x01DD,
  Win335_ZoneDownOpcode_ResumeEventScene128 = 0x01DE,
  Win335_ZoneDownOpcode_ResumeEventScene255 = 0x01DF,
  Win335_ZoneDownOpcode_Quests = 0x01E0,
  Win335_ZoneDownOpcode_Quest = 0x01E1,
  Win335_ZoneDownOpcode_QuestCompleteFlags = 0x01E2,
  Win335_ZoneDownOpcode_QuestCompleteFlag = 0x01E3,
  Win335_ZoneDownOpcode_Guildleves = 0x01E4,
  Win335_ZoneDownOpcode_Guildleve = 0x01E5,
  Win335_ZoneDownOpcode_LeveCompleteFlags = 0x01E6,
  Win335_ZoneDownOpcode_LeveCompleteFlag = 0x01E7,
  Win335_ZoneDownOpcode_Notice2 = 0x01E9,
  Win335_ZoneDownOpcode_Notice4 = 0x01EA,
  Win335_ZoneDownOpcode_Notice8 = 0x01EB,
  Win335_ZoneDownOpcode_Notice16 = 0x01EC,
  Win335_ZoneDownOpcode_Notice32 = 0x01ED,
  Win335_ZoneDownOpcode_Tracking = 0x01EE,
  Win335_ZoneDownOpcode_IsMarket = 0x01EF,
  Win335_ZoneDownOpcode_LegacyQuestCompleteFlags = 0x01F0,
  Win335_ZoneDownOpcode_ResumeEventSceneStr32 = 0x01F2,
  Win335_ZoneDownOpcode_LogText = 0x01F3,
  Win335_ZoneDownOpcode_ResumeEventScene2Str = 0x01FF,
  Win335_ZoneDownOpcode_Mount = 0x0200,
  Win335_ZoneDownOpcode_Unknown_0201 = 0x0201,
  Win335_ZoneDownOpcode_Director = 0x0226,
  Win335_ZoneDownOpcode_EventLogMessage2 = 0x0259,
  Win335_ZoneDownOpcode_EventLogMessage4 = 0x025A,
  Win335_ZoneDownOpcode_EventLogMessage8 = 0x025B,
  Win335_ZoneDownOpcode_EventLogMessage16 = 0x025C,
  Win335_ZoneDownOpcode_EventLogMessage32 = 0x025D,
  Win335_ZoneDownOpcode_BattleTalk2 = 0x0263,
  Win335_ZoneDownOpcode_BattleTalk4 = 0x0264,
  Win335_ZoneDownOpcode_BattleTalk8 = 0x0265,
  Win335_ZoneDownOpcode_EventReject = 0x026C,
  Win335_ZoneDownOpcode_MapMarker2 = 0x026D,
  Win335_ZoneDownOpcode_MapMarker4 = 0x026E,
  Win335_ZoneDownOpcode_MapMarker8 = 0x026F,
  Win335_ZoneDownOpcode_MapMarker16 = 0x0270,
  Win335_ZoneDownOpcode_MapMarker32 = 0x0271,
  Win335_ZoneDownOpcode_MapMarker64 = 0x0272,
  Win335_ZoneDownOpcode_MapMarker128 = 0x0273,
  Win335_ZoneDownOpcode_BalloonTalk2 = 0x0277,
  Win335_ZoneDownOpcode_BalloonTalk4 = 0x0278,
  Win335_ZoneDownOpcode_BalloonTalk8 = 0x0279,
  Win335_ZoneDownOpcode_WeatherId = 0x028A,
  Win335_ZoneDownOpcode_TitleList = 0x028B,
  Win335_ZoneDownOpcode_DiscoveryReply = 0x028C,
  Win335_ZoneDownOpcode_Unknown_028D = 0x028D,
  Win335_ZoneDownOpcode_ChocoboTaxiStart = 0x028E,
  Win335_ZoneDownOpcode_GMOrder2 = 0x0290,
  Win335_ZoneDownOpcode_GMOrder4 = 0x0291,
  Win335_ZoneDownOpcode_GMOrder8 = 0x0292,
  Win335_ZoneDownOpcode_GMOrder16 = 0x0293,
  Win335_ZoneDownOpcode_GMOrder32 = 0x0294,
  Win335_ZoneDownOpcode_InspectQuests = 0x029E,
  Win335_ZoneDownOpcode_InspectGuildleves = 0x029F,
  Win335_ZoneDownOpcode_InspectReward = 0x02A0,
  Win335_ZoneDownOpcode_InspectBeastReputation = 0x02A1,
  Win335_ZoneDownOpcode_Config = 0x02C6,
  Win335_ZoneDownOpcode_NpcYell = 0x02D0,
  Win335_ZoneDownOpcode_SwapSystem = 0x02D1,
  Win335_ZoneDownOpcode_FatePcWork = 0x02D2,
  Win335_ZoneDownOpcode_LootResult = 0x02D3,
  Win335_ZoneDownOpcode_FateAccessCollectionEventObject = 0x02D4,
  Win335_ZoneDownOpcode_FateSyncLimitTime = 0x02D5,
  Win335_ZoneDownOpcode_EnableLogout = 0x02D6,
  Win335_ZoneDownOpcode_LogMessage = 0x02D7,
  Win335_ZoneDownOpcode_FateContextWork = 0x02D9,
  Win335_ZoneDownOpcode_FateActiveRange = 0x02DA,
  Win335_ZoneDownOpcode_UpdateFindContent = 0x02DB,
  Win335_ZoneDownOpcode_Cabinet = 0x02DC,
  Win335_ZoneDownOpcode_Achievement = 0x02DD,
  Win335_ZoneDownOpcode_NotifyFindContentStatus = 0x02DE,
  Win335_ZoneDownOpcode_ColosseumResult44 = 0x02DF,
  Win335_ZoneDownOpcode_ColosseumResult88 = 0x02E0,
  Win335_ZoneDownOpcode_ResponsePenalties = 0x02E1,
  Win335_ZoneDownOpcode_ContentClearFlags = 0x02E2,
  Win335_ZoneDownOpcode_ContentAttainFlags = 0x02E3,
  Win335_ZoneDownOpcode_UpdateContent = 0x02E4,
  Win335_ZoneDownOpcode_Text = 0x02E5,
  Win335_ZoneDownOpcode_SuccessFindContentAsMember5 = 0x02E6,
  Win335_ZoneDownOpcode_CancelLogoutCountdown = 0x02E7,
  Win335_ZoneDownOpcode_SetEventBehavior = 0x02E8,
  Win335_ZoneDownOpcode_BallistaStart = 0x02E9,
  Win335_ZoneDownOpcode_RetainerCustomizePreset = 0x02EA,
  Win335_ZoneDownOpcode_FateReward = 0x02EB,
  Win335_ZoneDownOpcode_HouseList = 0x02EC,
  Win335_ZoneDownOpcode_House = 0x02ED,
  Win335_ZoneDownOpcode_YardObjectList = 0x02EE,
  Win335_ZoneDownOpcode_YardObject = 0x02F0,
  Win335_ZoneDownOpcode_Interior = 0x02F1,
  Win335_ZoneDownOpcode_HousingAuction = 0x02F2,
  Win335_ZoneDownOpcode_HousingProfile = 0x02F3,
  Win335_ZoneDownOpcode_HousingHouseName = 0x02F4,
  Win335_ZoneDownOpcode_HousingGreeting = 0x02F5,
  Win335_ZoneDownOpcode_CharaHousingLandData = 0x02F6,
  Win335_ZoneDownOpcode_CharaHousing = 0x02F7,
  Win335_ZoneDownOpcode_HousingWelcome = 0x02F8,
  Win335_ZoneDownOpcode_FurnitureListS = 0x02F9,
  Win335_ZoneDownOpcode_FurnitureListM = 0x02FA,
  Win335_ZoneDownOpcode_FurnitureListL = 0x02FB,
  Win335_ZoneDownOpcode_Furniture = 0x02FC,
  Win335_ZoneDownOpcode_VoteKickConfirm = 0x02FD,
  Win335_ZoneDownOpcode_HousingProfileList = 0x02FE,
  Win335_ZoneDownOpcode_HousingObjectTransform = 0x02FF,
  Win335_ZoneDownOpcode_HousingObjectColor = 0x0300,
  Win335_ZoneDownOpcode_HousingObjectTransformMulti = 0x0301,
  Win335_ZoneDownOpcode_ConfusionApproach = 0x0302,
  Win335_ZoneDownOpcode_ConfusionTurn = 0x0303,
  Win335_ZoneDownOpcode_ConfusionTurnCancel = 0x0304,
  Win335_ZoneDownOpcode_ConfusionCancel = 0x0305,
  Win335_ZoneDownOpcode_MIPMemberList = 0x0306,
  Win335_ZoneDownOpcode_HousingGetPersonalRoomProfileListResult = 0x0307,
  Win335_ZoneDownOpcode_HousingGetHouseBuddyStableListResult = 0x0308,
  Win335_ZoneDownOpcode_HouseTrainBuddyData = 0x0309,
  Win335_ZoneDownOpcode_Unknown_030A = 0x030A,
  Win335_ZoneDownOpcode_Unknown_030B = 0x030B,
  Win335_ZoneDownOpcode_Unknown_030C = 0x030C,
  Win335_ZoneDownOpcode_Unknown_030D = 0x030D,
  Win335_ZoneDownOpcode_Unknown_030E = 0x030E,
  Win335_ZoneDownOpcode_Unknown_030F = 0x030F,
  Win335_ZoneDownOpcode_Unknown_0310 = 0x0310,
  Win335_ZoneDownOpcode_Unknown_0311 = 0x0311,
  Win335_ZoneDownOpcode_FcChestLog = 0x0316,
  Win335_ZoneDownOpcode_SalvageResult = 0x0317,
  Win335_ZoneDownOpcode_DailyQuests = 0x0320,
  Win335_ZoneDownOpcode_DailyQuest = 0x0321,
  Win335_ZoneDownOpcode_QuestRepeatFlags = 0x0322,
  Win335_ZoneDownOpcode_HousingObjectTransformMultiResult = 0x032A,
  Win335_ZoneDownOpcode_HousingLogWithHouseName = 0x032B,
  Win335_ZoneDownOpcode_TreasureHuntReward = 0x032C,
  Win335_ZoneDownOpcode_HousingCombinedObjectStatus = 0x032D,
  Win335_ZoneDownOpcode_HouseBuddyModelData = 0x032E,
  Win335_ZoneDownOpcode_Unknown_032F = 0x032F,
  Win335_ZoneDownOpcode_Unknown_0330 = 0x0330,
  Win335_ZoneDownOpcode_Unknown_0331 = 0x0331,
  Win335_ZoneDownOpcode_Unknown_0332 = 0x0332,
  Win335_ZoneDownOpcode_Unknown_0333 = 0x0333,
  Win335_ZoneDownOpcode_Marker = 0x0334,
  Win335_ZoneDownOpcode_GroundMarker = 0x0335,
  Win335_ZoneDownOpcode_Frontline01Result = 0x0336,
  Win335_ZoneDownOpcode_Frontline01BaseInfo = 0x0337,
  Win335_ZoneDownOpcode_Unknown_0338 = 0x0338,
  Win335_ZoneDownOpcode_Unknown_0339 = 0x0339,
  Win335_ZoneDownOpcode_Unknown_033A = 0x033A,
  Win335_ZoneDownOpcode_UnMountLink = 0x033E,
  Win335_ZoneDownOpcode_Unknown_033F = 0x033F,
  Win335_ZoneDownOpcode_Unknown_0348 = 0x0348,
  Win335_ZoneDownOpcode_Unknown_0349 = 0x0349,
  Win335_ZoneDownOpcode_Unknown_034A = 0x034A,
  Win335_ZoneDownOpcode_Unknown_034B = 0x034B,
  Win335_ZoneDownOpcode_Unknown_034C = 0x034C,
  Win335_ZoneDownOpcode_Unknown_034D = 0x034D,
  Win335_ZoneDownOpcode_Unknown_034E = 0x034E,
  Win335_ZoneDownOpcode_Unknown_034F = 0x034F,
  Win335_ZoneDownOpcode_Unknown_0350 = 0x0350,
  Win335_ZoneDownOpcode_Unknown_0351 = 0x0351,
  Win335_ZoneDownOpcode_Unknown_0352 = 0x0352,
  Win335_ZoneDownOpcode_Unknown_0353 = 0x0353,
  Win335_ZoneDownOpcode_Unknown_0354 = 0x0354,
  Win335_ZoneDownOpcode_Unknown_0355 = 0x0355,
  Win335_ZoneDownOpcode_Unknown_0356 = 0x0356,
  Win335_ZoneDownOpcode_Unknown_0357 = 0x0357,
  Win335_ZoneDownOpcode_Unknown_0358 = 0x0358,
  Win335_ZoneDownOpcode_Unknown_0359 = 0x0359,
  Win335_ZoneDownOpcode_Unknown_035A = 0x035A,
  Win335_ZoneDownOpcode_Unknown_035B = 0x035B,
  Win335_ZoneDownOpcode_Unknown_035C = 0x035C,
  Win335_ZoneDownOpcode_Unknown_035D = 0x035D,
  Win335_ZoneDownOpcode_Unknown_035E = 0x035E,
  Win335_ZoneDownOpcode_Unknown_0384 = 0x0384,
  Win335_ZoneDownOpcode_Unknown_0385 = 0x0385,
  Win335_ZoneDownOpcode_Unknown_0386 = 0x0386,
  Win335_ZoneDownOpcode_Unknown_0387 = 0x0387,
  Win335_ZoneDownOpcode_Unknown_0388 = 0x0388,
  Win335_ZoneDownOpcode_Unknown_0389 = 0x0389,
  Win335_ZoneDownOpcode_Unknown_038A = 0x038A,
  Win335_ZoneDownOpcode_Unknown_03B7 = 0x03B7
};

enum Win335_ChatDownOpcode : unsigned __int16
{
  Win335_ChatDownOpcode_ChatFrom = 0x0064,
  Win335_ChatDownOpcode_Chat = 0x0065,
  Win335_ChatDownOpcode_TellNotFound = 0x0066,
  Win335_ChatDownOpcode_RecvBusyStatus = 0x0067,
  Win335_ChatDownOpcode_GetChannelMemberListResult = 0x0068,
  Win335_ChatDownOpcode_GetChannelListResult = 0x0069,
  Win335_ChatDownOpcode_RecvFinderStatus = 0x006A
};

struct Win335_ZoneIpcPacket
{
  unsigned __int16 reserved;
  Win335_ZoneDownOpcode opcode;
  unsigned __int16 padding;
  unsigned __int16 serverId;
  unsigned __int32 timestamp;
  unsigned __int32 padding1;
  unsigned __int8 payload[0x1000]; // inspection window; not an exact wire size
};

struct Win335_ChatIpcPacket
{
  unsigned __int16 reserved;
  Win335_ChatDownOpcode opcode;
  unsigned __int16 padding;
  unsigned __int16 serverId;
  unsigned __int32 timestamp;
  unsigned __int32 padding1;
  unsigned __int8 payload[0x1000]; // inspection window; not an exact wire size
};

struct Win335_PacketDispatcher
{
  void *zoneVftable;
  void *chatVftable;
  void *networkModuleProxy;
};

struct Win335_EventFramework;

struct Win335_Framework;

struct Win335_UIModule;

struct Win335_StorageManager;

struct Win335_InfoProxyInterface;

struct Win335_InfoProxyItemSearch;

struct Win335_Treasure;

struct Win335_TreasureManager;

struct Win335_InfoModule
{
  void *vftable;
  Win335_InfoProxyInterface *proxies[1]; // indexed array; one-element declaration does not assert the trailing class size
};

struct Win335_QuestWork_KnownFields
{
  unsigned __int8 _unknown_0000[0x8];
  unsigned __int16 questId;
  unsigned __int8 sequence;
};

struct Win335_LeveWork_KnownFields
{
  unsigned __int8 _unknown_0000[0x8];
  unsigned __int16 leveId;
};

struct Win335_ItemAssemblyFragment
{
  unsigned __int8 _unknown_0000[0x8];
  unsigned __int8 payload[0x50];
  Win335_ItemAssemblyFragment *previous;
  Win335_ItemAssemblyFragment *next;
};

struct Win335_ItemAssemblyContext
{
  unsigned __int8 _unknown_0000[0x10];
  unsigned __int32 targetActorId;
  unsigned __int8 _unknown_0014[0x4];
  Win335_ItemAssemblyFragment *firstFragment;
  Win335_ItemAssemblyFragment *lastFragment;
  unsigned __int32 receivedFragmentCount;
  signed __int32 expectedFragmentCount;
  Win335_ItemAssemblyContext *previous;
  Win335_ItemAssemblyContext *next;
};

struct Win335_ItemPacketAssembler
{
  unsigned __int8 _unknown_0000[0x10];
  Win335_ItemAssemblyFragment *freeFragmentHead;
  Win335_ItemAssemblyFragment *freeFragmentTail;
  unsigned __int8 _unknown_0020[0x8];
  Win335_ItemAssemblyContext *freeContextHead;
  Win335_ItemAssemblyContext *freeContextTail;
  Win335_ItemAssemblyContext *activeContextHead;
  Win335_ItemAssemblyContext *activeContextTail;
};

struct Win335_InviteResult_KnownFields
{
  unsigned __int32 Result; // +0x0: 32-bit result load
  unsigned __int8 AuthType; // +0x4: AuthType switch
};

struct Win335_InviteReplyResult_KnownFields
{
  unsigned __int8 _unknown_0000[0x4];
  unsigned __int8 AuthType; // +0x4: AuthType switch 1/2/4/5/6
};

struct Win335_InviteUpdate_KnownFields
{
  unsigned __int8 _unknown_0000[0xC];
  unsigned __int8 AuthType; // +0xC: AuthType switch
};

struct Win335_GetCommonlistResult_KnownFields
{
  unsigned __int8 _unknown_0000[0xC];
  unsigned __int8 ListType; // +0xC: proxy-selection switch
};

struct Win335_SetProfileResult_KnownFields
{
  unsigned __int8 _unknown_0000[0x10];
  unsigned __int32 Result; // +0x10: result branch
  unsigned __int8 CurrentSelectClassID; // +0x14: detail-proxy update
  unsigned __int8 Region; // +0x15: language/region update
  unsigned __int8 SearchComment[0xC1]; // +0x16: comment pointer
};

struct Win335_Create_KnownFields
{
  unsigned __int8 _unknown_0000[0x14];
  unsigned __int8 OwnerId[0x4]; // +0x14: local-owner comparison
  unsigned __int8 _unknown_0018[0x1B];
  unsigned __int8 ObjType[0x1]; // +0x33: ObjType == 2 test
};

struct Win335_PlayerStatusUpdate_KnownFields
{
  unsigned __int8 ClassJob; // +0x0: class/job update
  unsigned __int8 _unknown_0001[0x1];
  unsigned __int16 Lv; // +0x2: level update
  unsigned __int8 _unknown_0004[0x2];
  unsigned __int16 LvSync; // +0x6: 3.x synchronized-level load
  unsigned __int32 Exp; // +0x8: experience update
  unsigned __int32 RestPoint; // +0xC: rested experience update
};

struct Win335_PlayerStatus_KnownFields
{
  unsigned __int8 _unknown_0000[0x8];
  unsigned __int64 Crest; // +0x8: crest update
};

struct Win335_ChatFrom_KnownFields
{
  unsigned __int64 fromCharacterID; // +0x0: sender ID use
  unsigned __int8 type; // +0x8: chat-type branch
  unsigned __int8 fromName[0x20]; // +0x9: UTF-8 sender name
  unsigned __int8 message[0x400]; // +0x29: UTF-8 message
};

struct Win335_Chat_KnownFields
{
  unsigned __int64 channelID; // +0x0: channel proxy lookup
  unsigned __int64 speakerCharacterID; // +0x8: speaker log ID
  unsigned __int32 speakerEntityID; // +0x10: character lookup
  unsigned __int8 type; // +0x14: chat-type branch
  unsigned __int8 speakerName[0x20]; // +0x15: UTF-8 speaker name
  unsigned __int8 message[0x400]; // +0x35: UTF-8 message
};

struct Win335_TellNotFound_KnownFields
{
  unsigned __int8 toName[0x20]; // +0x0: payload converted to UTF-8 string
};

struct Win335_RecvBusyStatus_KnownFields
{
  unsigned __int8 toName[0x20]; // +0x0: payload converted to UTF-8 string
};

struct Win335_RecvFinderStatus_KnownFields
{
  unsigned __int8 toName[0x20]; // +0x0: payload converted to UTF-8 string
};

struct Win335_GetProfileResult_KnownFields
{
  unsigned __int64 OnlineStatus; // +0x0: status update
  unsigned __int64 SelectClassID; // +0x8: selected-class update
  unsigned __int8 CurrentSelectClassID; // +0x10: current-class update
  unsigned __int8 Region; // +0x11: language/region update
  unsigned __int8 SearchComment[0xC1]; // +0x12: comment pointer
};

struct Win335_GetSearchCommentResult_KnownFields
{
  unsigned __int32 TargetEntityID; // +0x0: entity ID argument
  unsigned __int8 SearchComment[0xC1]; // +0x4: comment pointer
};

struct Win335_ChatChannelResult_KnownFields
{
  unsigned __int64 ChannelID; // +0x0: channel-state update
  unsigned __int64 CommunityID; // +0x8: community comparison
  unsigned __int64 TargetCharacterID; // +0x10: target comparison
  unsigned __int32 UpPacketNo; // +0x18: 209/210 branch
  unsigned __int32 Result; // +0x1C: result branch
};

struct Win335_SendSystemMessage_KnownFields
{
  unsigned __int8 MessageParam; // +0x0: bit 1/4 tests
  unsigned __int8 Message[0x301]; // +0x1: UTF-8 message
};

struct Win335_SendLoginMessage_KnownFields
{
  unsigned __int8 MessageParam; // +0x0: bit 1/4 tests
  unsigned __int8 Message[0x301]; // +0x1: UTF-8 message
};

struct Win335_UpdateOnlineStatus_KnownFields
{
  unsigned __int64 OnlineStatus; // +0x0: 64-bit status forwarding
};

struct Win335_PartyRecruitResult_KnownFields
{
  unsigned __int8 _unknown_0000[0x10];
  unsigned __int32 Type; // +0x10: recruitment-mode switch
  unsigned __int32 Result; // +0x14: result/error branch
};

struct Win335_RequestItmeResult_KnownFields
{
  unsigned __int8 _unknown_0000[0x8];
  unsigned __int64 Param; // +0x8: wishlist parameter
  unsigned __int32 Type; // +0x10: wishlist-mode switch
  unsigned __int32 Result; // +0x14: result/error branch
};

struct Win335_AllianceReadyCheckResult_KnownFields
{
  unsigned __int8 EntityID[0x20]; // +0x0: entity-ID array
  unsigned __int8 Ready[0x8]; // +0x20: ready-state array
  unsigned __int8 Count; // +0x28: entry count
};

struct Win335_PcPartyResult_KnownFields
{
  unsigned __int32 UpPacketNo; // +0x0: party operation
  unsigned __int32 Result; // +0x4: error/result branch
};

struct Win335_PcPartyUpdate_KnownFields
{
  unsigned __int64 ExecuteCharacterID; // +0x0: executor ID
  unsigned __int64 TargetCharacterID; // +0x8: target ID
  unsigned __int8 ExecuteIdentity; // +0x10: executor identity
  unsigned __int8 TargetIdentity; // +0x11: target identity
  unsigned __int8 UpdateStatus; // +0x12: party-update switch
  unsigned __int8 Count; // +0x13: party count
  unsigned __int8 ExecuteCharacterName[0x20]; // +0x14: executor name
  unsigned __int8 TargetCharacterName[0x20]; // +0x34: target name
};

struct Win335_InviteCancelResult_KnownFields
{
  unsigned __int32 Result; // +0x0: result field layout
  unsigned __int8 AuthType; // +0x4: party AuthType test
};

struct Win335_QuestCompleteFlags_KnownFields
{
  unsigned __int8 completeFlagArray[0xC8]; // +0x0: Windows copies 0x136 bytes; PS3 copies 0xC8 bytes
  unsigned __int8 _unknown_00C8[0x6E];
  unsigned __int8 unknownCompleteMask[0x20]; // +0x136: Windows dispatcher forwards a second 32-byte region at payload +0x136
};

struct Win335_QuestCompleteFlag_KnownFields
{
  unsigned __int16 bitIndex; // +0x0: quest-completion bit index
  unsigned __int8 completed; // +0x2: set/clear boolean
  unsigned __int8 update; // +0x3: EventFramework update boolean
  unsigned __int8 unknown4[0x1]; // +0x4: optional 3.x bitset/UI update index
};

struct Win335_LeveCompleteFlag_KnownFields
{
  unsigned __int16 bitIndex; // +0x0: leve-completion bit index
  unsigned __int8 completed; // +0x2: set/clear boolean
};

struct Win335_DailyQuests_KnownFields
{
  unsigned __int8 update; // +0x0: daily-quest synchronization update boolean
  unsigned __int8 _unknown_0001[0x3];
  unsigned __int8 dailyQuestArray[0x18]; // +0x4: 12 DailyQuest records in Windows versus 6 in PS3
  unsigned __int8 dailyQuestArray_6_11[0x18]; // +0x1C: Windows processes 12 four-byte records; PS3 processes 6
};

struct Win335_DailyQuest_KnownFields
{
  unsigned __int8 index; // +0x0: daily-quest slot index
  unsigned __int8 update; // +0x1: daily-quest synchronization update boolean
  unsigned __int8 _unknown_0002[0x2];
  unsigned __int8 dailyQuest[0x4]; // +0x4: quest ID and flags record
};

struct Win335_QuestRepeatFlags_KnownFields
{
  unsigned __int8 update; // +0x0: repeat-flag synchronization update boolean
  unsigned __int8 repeatFlagArray[0x1]; // +0x1: one-byte repeat-quest mask
};

#pragma pack(pop)
